import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import nextPackage from "next/package.json";
import { getTasksManager } from "applications/hooks/getTaskManager";

export default function Home({}) {
  const taskManager = getTasksManager();
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, Bun!</h1>
    </div>
  );
}
