import Head from "next/head";
import React from "react";
import { getTasksManager } from "applications/hooks/getTaskManager";

export default function Home({}) {
  const taskManager = getTasksManager();
  return (
    <div>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <nav className="flex justify-center p-5">
          <h1 className="text-4xl font-bold">Bun Todo App</h1>
        </nav>
        <h1 className="text-3xl font-bold">Hello, Bun!</h1>
      </div>
    </div>
  );
}
